import '../../controllers/runtime_data_controller.dart';
import '../phase1_schema.dart';
import 'base_repository.dart';

class GenericRepository extends BaseRepository {
  GenericRepository(super.service, super.client, {this.runtimeData});

  final RuntimeDataController? runtimeData;

  static const autoGeneratedFields = <String, Set<String>>{
    'customers': {'customer_code'},
    'customer_orders': {'order_number'},
    'customer_order_lines': {'line_no', 'product_description_snapshot'},
    'bom_items': {'line_no'},
    'routing_operations': {'sequence_no'},
    'checklist_items': {'sequence_no'},
    'quality_check_items': {'sequence_no'},
    'production_orders': {'op_number'},
    'deliveries': {'delivery_number'},
    'customer_claims': {'claim_number'},
    'nonconformities': {'nc_number'},
  };

  Future<List<Map<String, dynamic>>> listRows(
    DbTableSpec spec, {
    Map<String, dynamic> filters = const {},
  }) async {
    final hasOrg = spec.fields.any((f) => f.name == 'organization_id');
    final orderBy = _orderField(spec);
    if (hasOrg)
      return listTenant(spec.table, filters: filters, orderBy: orderBy);
    return service.list(spec.table, equals: filters, orderBy: orderBy);
  }

  Future<Map<String, dynamic>> createRow(
    DbTableSpec spec,
    Map<String, dynamic> values,
  ) async {
    final payload = _sanitize(spec, values, creating: true);
    if (spec.fields.any((f) => f.name == 'organization_id'))
      payload['organization_id'] = organizationId;
    _injectUserFields(spec, payload, creating: true);
    await _injectGenerated(spec, payload);
    final row = await service.insert(spec.table, payload);
    runtimeData?.tableChanged(spec.table);
    return row;
  }

  Future<Map<String, dynamic>> updateRow(
    DbTableSpec spec,
    String id,
    Map<String, dynamic> values,
  ) async {
    final payload = _sanitize(spec, values, creating: false);
    _injectUserFields(spec, payload, creating: false);
    final row = await service.update(spec.table, id, payload);
    runtimeData?.tableChanged(spec.table);
    return row;
  }

  Future<void> deleteRow(DbTableSpec spec, Map<String, dynamic> row) async {
    final id = row['id'];
    if (id != null) {
      await service.delete(spec.table, id.toString());
    } else {
      await service.deleteWhere(spec.table, identityFor(spec, row));
    }
    runtimeData?.tableChanged(spec.table);
  }

  Future<Map<String, dynamic>> updateAnyRow(
    DbTableSpec spec,
    Map<String, dynamic> original,
    Map<String, dynamic> values,
  ) async {
    final payload = _sanitize(spec, values, creating: false);
    _injectUserFields(spec, payload, creating: false);
    final id = original['id'];
    final row = id != null
        ? await service.update(spec.table, id.toString(), payload)
        : await service.updateWhere(
            spec.table,
            identityFor(spec, original),
            payload,
          );
    runtimeData?.tableChanged(spec.table);
    return row;
  }

  Map<String, dynamic> identityFor(DbTableSpec spec, Map<String, dynamic> row) {
    const composite = <String, List<String>>{
      'routing_operation_checklists': [
        'routing_operation_id',
        'checklist_template_id',
      ],
      'routing_operation_quality_checks': [
        'routing_operation_id',
        'quality_template_id',
      ],
    };
    final fields = composite[spec.table];
    if (fields == null)
      throw StateError(
        'La tabla ${spec.table} no tiene identidad editable configurada.',
      );
    return {for (final field in fields) field: row[field]};
  }

  Map<String, dynamic> _sanitize(
    DbTableSpec spec,
    Map<String, dynamic> values, {
    required bool creating,
  }) {
    final payload = <String, dynamic>{};
    for (final field in spec.fields) {
      if (field.readOnly || field.name == 'organization_id') continue;
      if (!creating && field.name == 'created_by') continue;
      if (creating &&
          (autoGeneratedFields[spec.table]?.contains(field.name) ?? false) &&
          (values[field.name] == null ||
              values[field.name].toString().trim().isEmpty))
        continue;
      if (!values.containsKey(field.name)) continue;
      final value = values[field.name];
      payload[field.name] = value == '' ? null : value;
    }
    return payload;
  }

  void _injectUserFields(
    DbTableSpec spec,
    Map<String, dynamic> payload, {
    required bool creating,
  }) {
    final names = spec.fields.map((e) => e.name).toSet();
    if (creating && names.contains('created_by'))
      payload['created_by'] = userId;
    if (names.contains('updated_by')) payload['updated_by'] = userId;
    if (creating && names.contains('uploaded_by'))
      payload['uploaded_by'] = userId;
    if (creating && names.contains('requested_by'))
      payload['requested_by'] = userId;
  }

  Future<void> _injectGenerated(
    DbTableSpec spec,
    Map<String, dynamic> payload,
  ) async {
    final org = organizationId;
    if (org == null && spec.fields.any((f) => f.name == 'organization_id'))
      throw StateError('No hay una organización seleccionada.');
    const sequenceKeys = <String, MapEntry<String, String>>{
      'customers': MapEntry('customer_code', 'CUSTOMER'),
      'customer_orders': MapEntry('order_number', 'ORDER'),
      'production_orders': MapEntry('op_number', 'OP'),
      'deliveries': MapEntry('delivery_number', 'DELIVERY'),
      'customer_claims': MapEntry('claim_number', 'CLAIM'),
      'nonconformities': MapEntry('nc_number', 'NC'),
    };
    final sequence = sequenceKeys[spec.table];
    if (sequence != null &&
        (payload[sequence.key] == null ||
            payload[sequence.key].toString().trim().isEmpty)) {
      payload[sequence.key] = await service.rpc(
        'next_sequence_value',
        params: {'p_org': org, 'p_key': sequence.value},
      );
    }

    if (spec.table == 'customer_order_lines') {
      payload['line_no'] ??= await _nextInt('customer_order_lines', 'line_no', {
        'customer_order_id': payload['customer_order_id'],
      }, step: 1);
      if (payload['product_description_snapshot'] == null &&
          payload['product_id'] != null) {
        final product = await service.one(
          'products',
          payload['product_id'].toString(),
        );
        payload['product_description_snapshot'] =
            product?['name']?.toString() ?? 'Producto';
      }
    }
    if (spec.table == 'bom_items')
      payload['line_no'] ??= await _nextInt('bom_items', 'line_no', {
        'bom_revision_id': payload['bom_revision_id'],
      }, step: 10);
    if (spec.table == 'bom_items') {
      payload.removeWhere((key, value) => value == null);
      if (payload['component_type'] != 'subassembly') {
        payload.remove('child_bom_revision_id');
        payload['is_phantom'] = false;
      }
      payload['quantity_basis'] ??= 'per_output_unit';
      if (payload['quantity_basis'] != 'formula') {
        payload.remove('quantity_formula');
        payload['quantity'] ??= 1;
      }
      if (!payload.containsKey('uom_id') &&
          payload['bom_revision_id'] != null) {
        final revision = await service.one(
          'bom_revisions',
          payload['bom_revision_id'].toString(),
        );
        final outputUomId = revision?['output_uom_id'];
        if (outputUomId != null) payload['uom_id'] = outputUomId;
      }
      payload['formula_language'] ??= 'pomgt-expression';
      payload['scrap_pct'] ??= 0;
      payload['expected_yield_pct'] ??= 100;
      payload['is_optional'] ??= false;
      payload['is_phantom'] ??= false;
      payload['issue_method'] ??= 'manual';
    }
    if (spec.table == 'routing_operations') {
      payload['sequence_no'] ??= await _nextInt(
        'routing_operations',
        'sequence_no',
        {'routing_revision_id': payload['routing_revision_id']},
        step: 10,
      );
      payload['operation_type'] ??= 'activity';
      payload['run_time_basis'] ??= 'fixed';
      payload['setup_time_minutes'] ??= 0;
      payload['queue_time_minutes'] ??= 0;
      payload['move_time_minutes'] ??= 0;
      payload['expected_scrap_pct'] ??= 0;
      payload['expected_yield_pct'] ??= 100;
      payload['formula_language'] ??= 'pomgt-expression';

      if (payload['run_time_basis'] == 'formula') {
        payload['run_time_value'] = null;
        payload['run_time_formula'] ??= '0';
      } else {
        payload['run_time_value'] ??= 0;
        payload['run_time_formula'] = null;
      }

      if (payload['operation_code'] == null ||
          payload['operation_code'].toString().trim().isEmpty) {
        payload['operation_code'] = 'PASO-${payload['sequence_no']}';
      }
    }
    if (spec.table == 'checklist_items')
      payload['sequence_no'] ??= await _nextInt(
        'checklist_items',
        'sequence_no',
        {'checklist_template_id': payload['checklist_template_id']},
        step: 10,
      );
    if (spec.table == 'quality_check_items')
      payload['sequence_no'] ??= await _nextInt(
        'quality_check_items',
        'sequence_no',
        {'quality_template_id': payload['quality_template_id']},
        step: 10,
      );
  }

  Future<int> _nextInt(
    String table,
    String field,
    Map<String, dynamic> filters, {
    required int step,
  }) async {
    final rows = await service.list(
      table,
      equals: filters,
      orderBy: field,
      ascending: false,
      limit: 1,
    );
    if (rows.isEmpty) return step;
    return ((rows.first[field] as num?)?.toInt() ?? 0) + step;
  }

  String? _orderField(DbTableSpec spec) {
    for (final candidate in [
      'legal_name',
      'name',
      'order_date',
      'sequence_no',
      'line_no',
      'created_at',
    ]) {
      if (spec.fields.any((f) => f.name == candidate)) return candidate;
    }
    return null;
  }
}
