class UiCopy {
  const UiCopy._();

  static const tableTitles = <String, String>{
    'organizations': 'Organización',
    'currencies': 'Monedas',
    'organization_members': 'Miembros de la organización',
    'payment_terms': 'Condiciones de pago',
    'uom_categories': 'Categorías de unidades',
    'units_of_measure': 'Unidades de medida',
    'number_sequences': 'Foliadores',
    'documents': 'Documentos',
    'document_versions': 'Versiones de documento',
    'customers': 'Clientes',
    'customer_addresses': 'Direcciones del cliente',
    'customer_contacts': 'Contactos del cliente',
    'customer_contact_emails': 'Correos del contacto',
    'customer_contact_phones': 'Teléfonos del contacto',
    'product_categories': 'Categorías de producto',
    'material_categories': 'Categorías de material',
    'product_types': 'Tipos de producto',
    'material_types': 'Tipos de material',
    'products': 'Productos',
    'product_revisions': 'Revisiones de producto',
    'product_tolerances': 'Tolerancias del producto',
    'product_custom_field_definitions': 'Campos personalizados',
    'product_custom_field_options': 'Opciones de campos personalizados',
    'product_revision_custom_values': 'Valores personalizados de revisión',
    'customer_products': 'Productos del cliente',
    'customer_requirements': 'Requisitos del cliente',
    'design_approvals': 'Diseños aprobados',
    'customer_orders': 'Pedidos',
    'customer_order_lines': 'Líneas del pedido',
    'boms': 'Estructuras de fabricación',
    'bom_revisions': 'Revisiones de estructura de fabricación',
    'bom_items': 'Componentes de la estructura de fabricación',
    'bom_item_substitutes': 'Sustitutos de material',
    'work_centers': 'Centros de trabajo',
    'machines': 'Máquinas',
    'machine_parameter_definitions': 'Parámetros de máquina',
    'labor_roles': 'Roles de personal',
    'process_definitions': 'Procesos estándar',
    'routings': 'Rutas de fabricación',
    'routing_revisions': 'Revisiones de ruta de fabricación',
    'routing_operations': 'Operaciones de fabricación',
    'routing_operation_dependencies': 'Dependencias entre operaciones',
    'routing_operation_materials': 'Materiales por operación',
    'routing_operation_labor_requirements': 'Personal requerido por operación',
    'routing_operation_machine_parameters':
        'Parámetros de máquina por operación',
    'checklist_templates': 'Plantillas de verificación',
    'checklist_items': 'Puntos de verificación',
    'routing_operation_checklists': 'Verificaciones por operación',
    'quality_check_templates': 'Plantillas de calidad',
    'quality_check_items': 'Puntos de calidad',
    'routing_operation_quality_checks': 'Controles de calidad por operación',
    'routing_operation_cost_components': 'Componentes de costo por operación',
    'production_orders': 'Órdenes de producción',
    'production_order_allocations': 'Asignaciones a producción',
    'production_order_costs': 'Costos de órdenes de producción',
    'deliveries': 'Entregas',
    'delivery_lines': 'Líneas de entrega',
    'customer_claims': 'Reclamaciones del cliente',
    'nonconformities': 'No conformidades',
    'document_links': 'Vínculos de documentos',
  };

  static const tableDescriptions = <String, String>{
    'organizations': 'Datos generales de la empresa que utiliza POMGT.',
    'currencies': 'Monedas disponibles para clientes, pedidos y costos.',
    'organization_members': 'Usuarios autorizados dentro de la organización.',
    'payment_terms':
        'Condiciones de pago reutilizables para clientes y pedidos.',
    'uom_categories':
        'Familias de unidades compatibles, por ejemplo cantidad, longitud, área o masa.',
    'units_of_measure': 'Unidades de medida y sus conversiones.',
    'number_sequences': 'Configuración de folios automáticos del sistema.',
    'documents': 'Repositorio documental con control de versiones.',
    'document_versions': 'Archivos físicos que pertenecen a un documento.',
    'customers': 'Información fiscal, comercial y operativa del cliente.',
    'customer_addresses':
        'Direcciones de facturación, envío, planta u oficina.',
    'customer_contacts': 'Personas de contacto y preferencias de comunicación.',
    'customer_contact_emails': 'Correos asociados a una persona de contacto.',
    'customer_contact_phones':
        'Teléfonos y WhatsApp asociados a una persona de contacto.',
    'product_categories': 'Clasificación simple de productos.',
    'material_categories':
        'Clasificación simple de materias primas, insumos y empaques.',
    'product_types':
        'Tipos comerciales de producto que cada empresa puede crear y administrar.',
    'material_types':
        'Tipos de material configurables como pintura, tinta, adhesivo o herramienta.',
    'products':
        'Catálogo maestro de productos, subensambles, materiales, consumibles, empaques, herramientas y servicios.',
    'product_revisions':
        'Versiones técnicas de un producto con especificaciones congeladas.',
    'product_tolerances':
        'Tolerancias medibles asociadas a una revisión de producto.',
    'product_custom_field_definitions':
        'Propiedades adicionales configurables sin modificar el código.',
    'product_custom_field_options':
        'Opciones permitidas para campos de selección.',
    'product_revision_custom_values':
        'Valores de campos personalizados para una revisión.',
    'customer_products':
        'Relación entre un cliente y los productos que compra.',
    'customer_requirements':
        'Especificaciones, instrucciones, procesos especiales, calidad y empaque requeridos por el cliente.',
    'design_approvals': 'Diseños o artes aprobados por el cliente.',
    'customer_orders':
        'Necesidades de producción provenientes de pedido, OC, orden interna, pronóstico o reposición.',
    'customer_order_lines':
        'Productos, cantidades y condiciones de cada pedido.',
    'boms': 'Cabeceras de estructuras de fabricación asociadas a productos.',
    'bom_revisions':
        'Versiones históricas o vigentes de una estructura de fabricación.',
    'bom_items':
        'Materiales, subensambles, consumibles y empaques requeridos por una revisión.',
    'bom_item_substitutes':
        'Alternativas permitidas para un material o componente.',
    'work_centers': 'Áreas donde se ejecutan operaciones de fabricación.',
    'machines': 'Equipos disponibles en los centros de trabajo.',
    'machine_parameter_definitions':
        'Parámetros configurables de las máquinas.',
    'labor_roles': 'Roles de personal y costos estándar.',
    'process_definitions': 'Biblioteca de procesos productivos reutilizables.',
    'routings': 'Rutas que definen cómo se fabrica un producto.',
    'routing_revisions': 'Versiones de una ruta de fabricación.',
    'routing_operations':
        'Operaciones secuenciadas con recursos, tiempos e instrucciones.',
    'routing_operation_dependencies':
        'Relaciones de precedencia entre operaciones.',
    'routing_operation_materials':
        'Materiales que se consumen en una operación.',
    'routing_operation_labor_requirements':
        'Personal requerido para ejecutar una operación.',
    'routing_operation_machine_parameters':
        'Valores esperados de máquina para una operación.',
    'checklist_templates':
        'Plantillas reutilizables de verificación operativa.',
    'checklist_items': 'Preguntas o verificaciones que componen una plantilla.',
    'routing_operation_checklists':
        'Plantillas de verificación asignadas a una operación.',
    'quality_check_templates':
        'Plantillas reutilizables para inspecciones de calidad.',
    'quality_check_items':
        'Mediciones o validaciones de una plantilla de calidad.',
    'routing_operation_quality_checks':
        'Controles de calidad asignados a una operación.',
    'routing_operation_cost_components':
        'Costos planeados asociados a una operación.',
    'production_orders':
        'Órdenes de producción generadas desde pedidos o necesidades internas.',
    'production_order_allocations':
        'Distribución de líneas de pedido entre órdenes de producción.',
    'production_order_costs':
        'Costo estimado y real de cada orden de producción.',
    'deliveries': 'Entregas realizadas al cliente.',
    'delivery_lines': 'Productos y cantidades incluidas en una entrega.',
    'customer_claims':
        'Reclamaciones del cliente y seguimiento de su resolución.',
    'nonconformities': 'No conformidades de cliente o producción.',
    'document_links': 'Relaciones entre documentos y entidades del sistema.',
  };

  static const _exact = <String, String>{
    'id': 'Identificador',
    'organization_id': 'Organización',
    'customer_code': 'Código de cliente',
    'legal_name': 'Razón social',
    'trade_name': 'Nombre comercial',
    'tax_id': 'RFC / identificación fiscal',
    'tax_country_code': 'País fiscal',
    'country_code': 'País',
    'website': 'Sitio web',
    'default_currency_code': 'Moneda predeterminada',
    'currency_code': 'Moneda',
    'payment_term_id': 'Condición de pago',
    'customer_id': 'Cliente',
    'address_type': 'Tipo de dirección',
    'attention_to': 'Atención a',
    'line1': 'Dirección',
    'line2': 'Dirección adicional',
    'state_region': 'Estado / Provincia',
    'postal_code': 'Código postal',
    'is_default_billing': 'Dirección predeterminada de facturación',
    'is_default_shipping': 'Dirección predeterminada de envío',
    'delivery_notes': 'Indicaciones de entrega',
    'full_name': 'Nombre completo',
    'job_title': 'Puesto',
    'preferred_language': 'Idioma preferido',
    'receives_order_updates': 'Recibe actualizaciones de pedidos',
    'receives_quality_updates': 'Recibe actualizaciones de calidad',
    'contact_id': 'Contacto',
    'email': 'Correo electrónico',
    'phone_number': 'Teléfono',
    'is_mobile': 'Es móvil',
    'is_whatsapp': 'Usa WhatsApp',
    'is_primary': 'Principal',
    'is_verified': 'Verificado',
    'is_active': 'Activo',
    'created_at': 'Fecha de creación',
    'updated_at': 'Última actualización',
    'created_by': 'Creado por',
    'updated_by': 'Actualizado por',
    'code': 'Código',
    'name': 'Nombre',
    'description': 'Descripción',
    'category_id': 'Categoría',
    'material_category_id': 'Categoría de material',
    'product_type_catalog_id': 'Tipo de producto',
    'material_type_id': 'Tipo de material',
    'product_type': 'Clasificación del sistema',
    'system_class': 'Clasificación del sistema',
    'sku': 'SKU',
    'owner_customer_id': 'Cliente propietario',
    'base_uom_id': 'Unidad base',
    'uom_id': 'Unidad de medida',
    'dimension_uom_id': 'Unidad de dimensiones',
    'weight_uom_id': 'Unidad de peso',
    'output_uom_id': 'Unidad de salida',
    'is_manufacturable': 'Se fabrica',
    'is_purchasable': 'Se compra',
    'is_sellable': 'Se vende',
    'is_customer_specific': 'Específico de un cliente',
    'track_lots': 'Rastrear por lote',
    'track_serials': 'Rastrear por número de serie',
    'default_lead_time_days': 'Tiempo de entrega estándar (días)',
    'product_id': 'Producto',
    'product_revision_id': 'Revisión de producto',
    'revision_code': 'Código de revisión',
    'revision_no': 'Número de revisión',
    'effective_from': 'Vigente desde',
    'effective_to': 'Vigente hasta',
    'width': 'Ancho',
    'height': 'Alto',
    'length': 'Largo',
    'thickness': 'Grosor',
    'material_description': 'Material',
    'color_description': 'Color',
    'weight': 'Peso',
    'tolerance_notes': 'Notas de tolerancias',
    'quality_notes': 'Requisitos de calidad',
    'packaging_notes': 'Requisitos de empaque',
    'image_document_version_id': 'Imagen del producto',
    'customer_sku': 'SKU del cliente',
    'customer_product_name': 'Nombre usado por el cliente',
    'preferred_revision_id': 'Revisión preferida',
    'default_ship_to_address_id': 'Dirección de envío predeterminada',
    'requirement_type': 'Tipo de requisito',
    'structured_data': 'Datos estructurados',
    'document_version_id': 'Versión de documento',
    'approval_status': 'Estado de aprobación',
    'approved_by_name': 'Aprobado por',
    'approved_at': 'Fecha de aprobación',
    'expires_at': 'Fecha de vencimiento',
    'source_type': 'Origen del pedido',
    'order_number': 'Número de pedido',
    'customer_po_number': 'OC del cliente',
    'external_reference': 'Referencia externa',
    'order_date': 'Fecha del pedido',
    'requested_delivery_date': 'Fecha solicitada de entrega',
    'billing_address_id': 'Dirección de facturación',
    'shipping_address_id': 'Dirección de envío',
    'billing_address_snapshot': 'Copia histórica de dirección de facturación',
    'shipping_address_snapshot': 'Copia histórica de dirección de envío',
    'customer_contact_id': 'Contacto del cliente',
    'special_instructions': 'Instrucciones especiales',
    'line_no': 'Línea',
    'customer_product_id': 'Producto del cliente',
    'product_description_snapshot': 'Descripción histórica del producto',
    'requested_quantity': 'Cantidad solicitada',
    'unit_price': 'Precio unitario',
    'discount_pct': 'Descuento (%)',
    'tax_pct': 'Impuesto (%)',
    'line_status': 'Estado de la línea',
    'requirement_snapshot': 'Copia histórica de requisitos',
    'bom_id': 'Estructura de fabricación',
    'bom_code': 'Código de estructura de fabricación',
    'bom_revision_id': 'Revisión de estructura de fabricación',
    'child_bom_revision_id':
        'Revisión de estructura de fabricación del subensamble',
    'is_default': 'Predeterminado',
    'output_quantity': 'Cantidad base de salida',
    'expected_scrap_pct': 'Merma esperada (%)',
    'expected_yield_pct': 'Rendimiento esperado (%)',
    'component_type': 'Tipo de componente',
    'component_product_id': 'Material / componente',
    'component_product_revision_id': 'Revisión del componente',
    'quantity_basis': 'Forma de cálculo de cantidad',
    'quantity': 'Cantidad',
    'quantity_formula': 'Fórmula de cantidad',
    'formula_language': 'Motor de fórmula',
    'scrap_pct': 'Merma (%)',
    'is_optional': 'Opcional',
    'is_phantom': 'Subensamble fantasma',
    'issue_method': 'Método de consumo',
    'bom_item_id': 'Componente de la estructura',
    'substitute_product_id': 'Material sustituto',
    'substitute_product_revision_id': 'Revisión del sustituto',
    'conversion_ratio': 'Relación de conversión',
    'max_share_pct': 'Participación máxima (%)',
    'approval_required': 'Requiere aprobación',
    'valid_from': 'Válido desde',
    'valid_to': 'Válido hasta',
    'routing_id': 'Ruta de fabricación',
    'routing_code': 'Código de ruta',
    'routing_revision_id': 'Revisión de ruta',
    'routing_operation_id': 'Operación',
    'work_center_id': 'Centro de trabajo',
    'machine_id': 'Máquina',
    'preferred_machine_id': 'Máquina preferida',
    'sequence_no': 'Secuencia',
    'setup_time_minutes': 'Tiempo de preparación (min)',
    'run_time_basis': 'Forma de cálculo del tiempo',
    'run_time_minutes': 'Tiempo de ejecución (min)',
    'run_time_per_unit_minutes': 'Tiempo por unidad (min)',
    'run_time_formula': 'Fórmula de tiempo',
    'queue_time_minutes': 'Tiempo de espera (min)',
    'move_time_minutes': 'Tiempo de traslado (min)',
    'labor_role_id': 'Rol de personal',
    'headcount': 'Número de personas',
    'involvement_pct': 'Participación (%)',
    'machine_parameter_definition_id': 'Parámetro de máquina',
    'target_value': 'Valor objetivo',
    'lower_value': 'Límite inferior',
    'upper_value': 'Límite superior',
    'checklist_template_id': 'Plantilla de verificación',
    'quality_template_id': 'Plantilla de calidad',
    'prompt': 'Pregunta / verificación',
    'response_type': 'Tipo de respuesta',
    'is_mandatory': 'Obligatorio',
    'check_type': 'Tipo de control',
    'nominal_value': 'Valor nominal',
    'allowed_values': 'Valores permitidos',
    'is_critical': 'Crítico',
    'op_number': 'Número de OP',
    'planned_quantity': 'Cantidad planificada',
    'planned_start_at': 'Inicio planificado',
    'planned_finish_at': 'Fin planificado',
    'required_at': 'Fecha requerida',
    'production_order_id': 'Orden de producción',
    'allocated_quantity': 'Cantidad asignada',
    'material_estimated': 'Material estimado',
    'material_actual': 'Material real',
    'labor_estimated': 'Mano de obra estimada',
    'labor_actual': 'Mano de obra real',
    'machine_estimated': 'Máquina estimada',
    'machine_actual': 'Máquina real',
    'subcontract_estimated': 'Subcontrato estimado',
    'subcontract_actual': 'Subcontrato real',
    'overhead_estimated': 'Indirectos estimados',
    'overhead_actual': 'Indirectos reales',
    'other_estimated': 'Otros estimados',
    'other_actual': 'Otros reales',
    'document_code': 'Código de documento',
    'title': 'Título',
    'document_type': 'Tipo de documento',
    'confidentiality': 'Confidencialidad',
    'version_no': 'Número de versión',
    'version_label': 'Etiqueta de versión',
    'original_filename': 'Nombre del archivo',
    'storage_provider': 'Proveedor de almacenamiento',
    'bucket_name': 'Contenedor de almacenamiento',
    'object_path': 'Ruta del archivo',
    'mime_type': 'Tipo de archivo',
    'size_bytes': 'Tamaño',
    'checksum_sha256': 'Huella SHA-256',
    'change_notes': 'Notas de cambio',
    'uploaded_by': 'Cargado por',
    'uploaded_at': 'Fecha de carga',
    'is_current': 'Versión actual',
    'pinned_version_id': 'Versión fijada',
    'purpose': 'Propósito',

    'actual_end_at': 'Fin real',
    'actual_labor': 'Mano de obra real',
    'actual_machine': 'Máquina real',
    'actual_material': 'Material real',
    'actual_overhead': 'Indirectos reales',
    'actual_start_at': 'Inicio real',
    'actual_subcontract': 'Subcontrato real',
    'amount_or_rate': 'Importe / tarifa',
    'approved_by': 'Aprobado por',
    'approved_by_contact_id': 'Contacto que aprobó',
    'area': 'Área',
    'attribute_name': 'Atributo',
    'carrier': 'Transportista',
    'category': 'Categoría',
    'city': 'Ciudad',
    'claim_number': 'Número de reclamación',
    'closed_at': 'Fecha de cierre',
    'completed_at': 'Fecha de finalización',
    'completed_quantity': 'Cantidad completada',
    'confirmed_at': 'Fecha de confirmación',
    'consumption_point': 'Momento de consumo',
    'containment_action': 'Acción de contención',
    'conversion_to_base': 'Conversión a unidad base',
    'corrective_action': 'Acción correctiva',
    'cost_basis': 'Base de costo',
    'cost_type': 'Tipo de costo',
    'customer_claim_id': 'Reclamación del cliente',
    'customer_order_id': 'Pedido',
    'customer_order_line_id': 'Línea del pedido',
    'daily_capacity_minutes': 'Capacidad diaria (min)',
    'data_type': 'Tipo de dato',
    'decimal_places': 'Decimales',
    'decimal_precision': 'Precisión decimal',
    'default_revision_id': 'Revisión predeterminada',
    'default_shipping_address_id': 'Dirección de envío predeterminada',
    'default_value': 'Valor predeterminado',
    'default_work_center_id': 'Centro de trabajo predeterminado',
    'delivered_date': 'Fecha de entrega',
    'delivery_id': 'Entrega',
    'delivery_number': 'Número de entrega',
    'department': 'Departamento',
    'dependency_type': 'Tipo de dependencia',
    'destination_snapshot': 'Copia histórica del destino',
    'detected_at': 'Fecha de detección',
    'display_name': 'Nombre para mostrar',
    'disposition': 'Disposición',
    'document_id': 'Documento',
    'due_days': 'Días para vencimiento',
    'early_payment_days': 'Días para pronto pago',
    'early_payment_discount_pct': 'Descuento por pronto pago (%)',
    'estimated_labor': 'Mano de obra estimada',
    'estimated_machine': 'Máquina estimada',
    'estimated_material': 'Material estimado',
    'estimated_overhead': 'Indirectos estimados',
    'estimated_subcontract': 'Subcontrato estimado',
    'execution_order': 'Orden de ejecución',
    'extension': 'Extensión',
    'external_service': 'Servicio externo',
    'field_definition_id': 'Definición de campo',
    'field_key': 'Clave del campo',
    'fixed_external_cost': 'Costo externo fijo',
    'formula_expression': 'Expresión de fórmula',
    'general_tolerance_notes': 'Notas generales de tolerancia',
    'help_text': 'Texto de ayuda',
    'hourly_cost': 'Costo por hora',
    'hourly_overhead_cost': 'Costo indirecto por hora',
    'instructions': 'Instrucciones',
    'is_base_unit': 'Unidad base',
    'is_filterable': 'Disponible como filtro',
    'is_required': 'Requerido',
    'joined_at': 'Fecha de incorporación',
    'label': 'Etiqueta',
    'lag_minutes': 'Desfase (min)',
    'last_recalculated_at': 'Último recálculo',
    'locale': 'Idioma / región',
    'lot_or_serial_reference': 'Lote / serie de referencia',
    'lower_limit': 'Límite inferior',
    'machine_code': 'Código de máquina',
    'manufacturer': 'Fabricante',
    'material_product_id': 'Material',
    'max_value': 'Valor máximo',
    'measurement_method': 'Método de medición',
    'min_value': 'Valor mínimo',
    'model': 'Modelo',
    'nc_number': 'Número de no conformidad',
    'next_value': 'Siguiente valor',
    'nonconformity_id': 'No conformidad',
    'notes': 'Notas',
    'opened_at': 'Fecha de apertura',
    'operation_code': 'Código interno del paso',
    'operation_type': 'Tipo de paso',
    'operation_id': 'Operación',
    'option_label': 'Etiqueta de opción',
    'option_value': 'Valor de opción',
    'owner_user_id': 'Usuario responsable',
    'padding': 'Longitud numérica',
    'parameter_definition_id': 'Definición de parámetro',
    'parameter_key': 'Clave del parámetro',
    'planned_end_at': 'Fin planificado',
    'predecessor_operation_id': 'Operación predecesora',
    'prefix': 'Prefijo',
    'priority': 'Prioridad',
    'process_code': 'Código de proceso',
    'process_definition_id': 'Proceso',
    'quantity_override': 'Cantidad ajustada',
    'requested_at': 'Fecha de solicitud',
    'requested_by': 'Solicitado por',
    'requested_resolution': 'Resolución solicitada',
    'required_predecessor_completion_pct':
        'Avance requerido de la predecesora (%)',
    'requires_checklist': 'Requiere lista de verificación',
    'requires_quality': 'Requiere control de calidad',
    'resolution': 'Resolución',
    'revision_label': 'Etiqueta de revisión',
    'root_cause': 'Causa raíz',
    'run_time_value': 'Valor de tiempo de ejecución',
    'separator': 'Separador',
    'sequence_key': 'Clave de secuencia',
    'serial_number': 'Número de serie',
    'setup_hourly_cost': 'Costo de preparación por hora',
    'severity': 'Severidad',
    'ship_date': 'Fecha de envío',
    'sort_order': 'Orden',
    'source_document_id': 'Documento origen',
    'source_document_version_id': 'Versión del documento origen',
    'status': 'Estado',
    'subject': 'Asunto',
    'symbol': 'Símbolo',
    'timezone': 'Zona horaria',
    'tracking_number': 'Número de rastreo',
    'trigger_point': 'Momento de control',
    'upper_limit': 'Límite superior',
    'user_id': 'Usuario',
    'valid_until': 'Válido hasta',
    'validation_rules': 'Reglas de validación',
    'value_boolean': 'Valor Sí / No',
    'value_date': 'Valor de fecha',
    'value_json': 'Valor estructurado',
    'value_number': 'Valor numérico',
    'value_text': 'Valor de texto',
    'version': 'Versión',
  };

  static const _words = <String, String>{
    'actual': 'real',
    'active': 'activo',
    'address': 'dirección',
    'allocated': 'asignada',
    'allowed': 'permitidos',
    'amount': 'importe',
    'approval': 'aprobación',
    'approved': 'aprobado',
    'area': 'área',
    'attention': 'atención',
    'attribute': 'atributo',
    'base': 'base',
    'billing': 'facturación',
    'bucket': 'contenedor',
    'carrier': 'transportista',
    'category': 'categoría',
    'change': 'cambio',
    'child': 'hija',
    'city': 'ciudad',
    'claim': 'reclamación',
    'closed': 'cerrado',
    'code': 'código',
    'color': 'color',
    'completed': 'completado',
    'component': 'componente',
    'confidentiality': 'confidencialidad',
    'confirmed': 'confirmado',
    'consumption': 'consumo',
    'contact': 'contacto',
    'containment': 'contención',
    'conversion': 'conversión',
    'corrective': 'correctiva',
    'cost': 'costo',
    'country': 'país',
    'created': 'creado',
    'currency': 'moneda',
    'customer': 'cliente',
    'daily': 'diaria',
    'data': 'datos',
    'date': 'fecha',
    'days': 'días',
    'decimal': 'decimales',
    'default': 'predeterminado',
    'delivered': 'entregado',
    'delivery': 'entrega',
    'department': 'departamento',
    'dependency': 'dependencia',
    'description': 'descripción',
    'destination': 'destino',
    'detected': 'detectado',
    'dimension': 'dimensión',
    'discount': 'descuento',
    'display': 'visualización',
    'disposition': 'disposición',
    'document': 'documento',
    'due': 'vencimiento',
    'early': 'anticipado',
    'effective': 'vigencia',
    'email': 'correo',
    'estimated': 'estimado',
    'execution': 'ejecución',
    'expected': 'esperado',
    'extension': 'extensión',
    'external': 'externa',
    'field': 'campo',
    'fixed': 'fijo',
    'formula': 'fórmula',
    'full': 'completo',
    'general': 'general',
    'headcount': 'personas',
    'height': 'alto',
    'help': 'ayuda',
    'hourly': 'por hora',
    'image': 'imagen',
    'instructions': 'instrucciones',
    'involvement': 'participación',
    'job': 'puesto',
    'joined': 'incorporación',
    'label': 'etiqueta',
    'labor': 'mano de obra',
    'lag': 'desfase',
    'last': 'último',
    'legal': 'razón social',
    'length': 'largo',
    'line': 'línea',
    'locale': 'idioma/región',
    'lot': 'lote',
    'lower': 'inferior',
    'machine': 'máquina',
    'manufacturer': 'fabricante',
    'material': 'material',
    'max': 'máximo',
    'measurement': 'medición',
    'mime': 'tipo de archivo',
    'min': 'mínimo',
    'model': 'modelo',
    'move': 'traslado',
    'name': 'nombre',
    'next': 'siguiente',
    'nominal': 'nominal',
    'notes': 'notas',
    'object': 'objeto',
    'opened': 'abierto',
    'operation': 'operación',
    'option': 'opción',
    'order': 'pedido',
    'organization': 'organización',
    'original': 'original',
    'output': 'salida',
    'owner': 'responsable',
    'packaging': 'empaque',
    'padding': 'relleno',
    'parameter': 'parámetro',
    'parent': 'superior',
    'payment': 'pago',
    'phone': 'teléfono',
    'pinned': 'fijada',
    'planned': 'planificado',
    'postal': 'postal',
    'predecessor': 'predecesora',
    'preferred': 'preferido',
    'prefix': 'prefijo',
    'priority': 'prioridad',
    'process': 'proceso',
    'product': 'producto',
    'production': 'producción',
    'prompt': 'pregunta',
    'purpose': 'propósito',
    'quality': 'calidad',
    'quantity': 'cantidad',
    'queue': 'espera',
    'receives': 'recibe',
    'requested': 'solicitado',
    'required': 'requerido',
    'requirement': 'requisito',
    'requires': 'requiere',
    'resolution': 'resolución',
    'response': 'respuesta',
    'revision': 'revisión',
    'root': 'raíz',
    'routing': 'ruta',
    'run': 'ejecución',
    'scrap': 'merma',
    'separator': 'separador',
    'sequence': 'secuencia',
    'serial': 'serie',
    'setup': 'preparación',
    'severity': 'severidad',
    'ship': 'envío',
    'shipping': 'envío',
    'size': 'tamaño',
    'sort': 'orden',
    'source': 'origen',
    'special': 'especial',
    'state': 'estado',
    'status': 'estado',
    'storage': 'almacenamiento',
    'structured': 'estructurados',
    'subject': 'asunto',
    'substitute': 'sustituto',
    'symbol': 'símbolo',
    'target': 'objetivo',
    'tax': 'impuesto',
    'thickness': 'grosor',
    'timezone': 'zona horaria',
    'title': 'título',
    'track': 'rastrear',
    'tracking': 'rastreo',
    'trade': 'comercial',
    'trigger': 'momento',
    'unit': 'unidad',
    'updated': 'actualizado',
    'uploaded': 'cargado',
    'upper': 'superior',
    'user': 'usuario',
    'valid': 'válido',
    'validation': 'validación',
    'value': 'valor',
    'version': 'versión',
    'website': 'sitio web',
    'weight': 'peso',
    'width': 'ancho',
    'work': 'trabajo',
    'center': 'centro',
    'number': 'número',
    'pct': '%',
    'minutes': 'minutos',
    'time': 'tiempo',
    'type': 'tipo',
    'method': 'método',
    'language': 'idioma',
    'current': 'actual',
    'primary': 'principal',
    'verified': 'verificado',
    'mobile': 'móvil',
    'whatsapp': 'WhatsApp',
    'optional': 'opcional',
    'phantom': 'fantasma',
    'mandatory': 'obligatorio',
    'critical': 'crítico',
    'filterable': 'filtrable',
    'manufacturable': 'fabricable',
    'purchasable': 'comprable',
    'sellable': 'vendible',
    'lots': 'lotes',
    'serials': 'series',
    'reference': 'referencia',
    'snapshot': 'copia histórica',
    'rate': 'tarifa',
    'overhead': 'indirectos',
    'subcontract': 'subcontrato',
    'point': 'punto',
    'share': 'participación',
    'ratio': 'relación',
    'yield': 'rendimiento',
    'basis': 'base',
    'issue': 'consumo',
    'finish': 'fin',
    'start': 'inicio',
    'role': 'rol',
    'template': 'plantilla',
    'check': 'control',
    'values': 'valores',
    'file': 'archivo',
    'filename': 'archivo',
    'path': 'ruta',
    'provider': 'proveedor',
    'confidential': 'confidencial',
    'system': 'sistema',
    'class': 'clasificación',
  };

  static const _enumLabels = <String, String>{
    'draft': 'Borrador',
    'active': 'Activo',
    'obsolete': 'Obsoleto',
    'archived': 'Archivado',
    'pending': 'Pendiente',
    'approved': 'Aprobado',
    'rejected': 'Rechazado',
    'expired': 'Vencido',
    'superseded': 'Reemplazado',
    'finished_good': 'Producto terminado',
    'semi_finished': 'Semiterminado',
    'raw_material': 'Materia prima',
    'consumable': 'Consumible',
    'packaging': 'Empaque',
    'tooling': 'Herramienta',
    'service': 'Servicio',
    'long_text': 'Texto largo',
    'integer': 'Entero',
    'decimal': 'Decimal',
    'customer_order': 'Pedido de cliente',
    'customer_po': 'OC del cliente',
    'internal_order': 'Orden interna',
    'forecast': 'Pronóstico',
    'inventory_replenishment': 'Reposición de inventario',
    'make_to_stock': 'Producción para inventario',
    'confirmed': 'Confirmado',
    'partially_released': 'Liberado parcialmente',
    'released': 'Liberado',
    'partially_completed': 'Completado parcialmente',
    'completed': 'Completado',
    'cancelled': 'Cancelado',
    'open': 'Abierto',
    'low': 'Baja',
    'normal': 'Normal',
    'high': 'Alta',
    'urgent': 'Urgente',
    'medium': 'Media',
    'critical': 'Crítica',
    'material': 'Material',
    'subassembly': 'Subensamble',
    'byproduct': 'Coproducto',
    'fixed': 'Fijo',
    'per_output_unit': 'Por unidad de salida',
    'formula': 'Fórmula',
    'manual': 'Manual',
    'backflush': 'Consumo automático',
    'at_operation_start': 'Al iniciar la operación',
    'at_operation_finish': 'Al terminar la operación',
    'available': 'Disponible',
    'busy': 'Produciendo',
    'setup': 'Preparación',
    'maintenance': 'Mantenimiento',
    'down': 'Detenida',
    'inactive': 'Inactiva',
    'per_unit': 'Por unidad',
    'finish_to_start': 'Fin → inicio',
    'start_to_start': 'Inicio → inicio',
    'finish_to_finish': 'Fin → fin',
    'start_to_finish': 'Inicio → fin',
    'boolean': 'Sí / No',
    'text': 'Texto',
    'number': 'Número',
    'date': 'Fecha',
    'select': 'Selección',
    'photo': 'Fotografía',
    'document': 'Documento',
    'multiselect': 'Selección múltiple',
    'json': 'Datos estructurados',
    'labor': 'Mano de obra',
    'machine': 'Máquina',
    'overhead': 'Indirectos',
    'subcontract': 'Subcontrato',
    'other': 'Otro',
    'per_hour': 'Por hora',
    'activity': 'Actividad',
    'external_service': 'Servicio externo',
    'planned': 'Planificada',
    'ready': 'Lista',
    'in_progress': 'En producción',
    'on_hold': 'En pausa',
    'shipped': 'Enviado',
    'partially_delivered': 'Entregado parcialmente',
    'delivered': 'Entregado',
    'under_review': 'En revisión',
    'action_required': 'Requiere acción',
    'resolved': 'Resuelto',
    'closed': 'Cerrado',
    'contained': 'Contenido',
    'under_investigation': 'En investigación',
    'rework': 'Retrabajo',
    'scrap': 'Desecho',
    'use_as_is': 'Usar como está',
    'return_to_supplier': 'Devolver a proveedor',
    'customer_concession': 'Concesión del cliente',
    'billing': 'Facturación',
    'shipping': 'Envío',
    'plant': 'Planta',
    'office': 'Oficina',
    'specification': 'Especificación',
    'special_process': 'Proceso especial',
    'instruction': 'Instrucción',
    'tolerance': 'Tolerancia',
    'quality_requirement': 'Requisito de calidad',
    'packaging_requirement': 'Requisito de empaque',
    'public': 'Público',
    'internal': 'Interno',
    'restricted': 'Restringido',
    'confidential': 'Confidencial',
    'before': 'Antes',
    'start': 'Inicio',
    'during': 'Durante',
    'finish': 'Final',
    'incoming': 'Recepción',
    'production': 'Producción',
    'final': 'Final',
    'customer_claim': 'Reclamación de cliente',
    'internal_audit': 'Auditoría interna',
    'work': 'Trabajo',
    'personal': 'Personal',
    'home': 'Casa',
    'main': 'Principal',
  };

  static const _singular = <String, String>{
    'customers': 'cliente',
    'product_categories': 'categoría',
    'material_categories': 'categoría de material',
    'product_types': 'tipo de producto',
    'material_types': 'tipo de material',
    'payment_terms': 'condición de pago',
    'units_of_measure': 'unidad de medida',
    'work_centers': 'centro de trabajo',
    'machines': 'máquina',
    'labor_roles': 'rol de personal',
    'process_definitions': 'proceso',
    'products': 'producto',
    'documents': 'documento',
  };

  static String tableTitle(String table, [String? fallback]) =>
      tableTitles[table] ?? fallback ?? table;
  static String tableDescription(String table, [String? fallback]) =>
      tableDescriptions[table] ?? fallback ?? '';
  static String createReferenceLabel(String table) =>
      'Agregar ${_singular[table] ?? tableTitle(table).toLowerCase()}';
  static String enumLabel(String value) =>
      _enumLabels[value] ?? fieldLabel(value);

  static String countryLabel(String code) {
    switch (code) {
      case 'MX':
        return 'México';
      case 'US':
        return 'Estados Unidos';
      default:
        return code;
    }
  }

  static String fieldLabel(String name, [String? fallback]) {
    if (_exact.containsKey(name)) return _exact[name]!;
    final tokens = name.split('_');
    final translated = tokens.map((t) => _words[t] ?? t).join(' ');
    if (translated.isEmpty) return fallback ?? name;
    return translated[0].toUpperCase() + translated.substring(1);
  }
}
